### ISSUE TITLE
formatter currency

### ISSUE THREAD

**Issue by candoa** [stewones/angular-morris-chart#26]
the formatter currency only work in the donut graph

**Comment by stewones** [comment]
@candoa 
sounds like the `formatter` attr is not present at all.  
@rolaveric can you help to implement this?

**Comment by rolaveric** [comment]
Can do.

**Comment by rolaveric** [comment]
Hmmmm, not as simple as I first suspected, or at least I need more specific details on what you want.

For donut graphs, I'm simply providing a way to pass through a value to the 'formatter' option that morris.js uses: http://morrisjs.github.io/morris.js/donuts.html

For [Line & Area graphs](http://morrisjs.github.io/morris.js/lines.html) there's a few related options that could be exposed:
- hoverCallback: Reformat the whole 'hover' output
- postUnits: Suffix for y-axis labels. eg. '%'
- preUnits: Prefix for y-axis labels. eg. '$'
- dateFormat: Formatter for the x-axis values (since they're expected to all be dates).
- xLabelFormat: Formatter for the x-axis labels
- yLabelFormat: Formatter for the y-axis labels

For [Bar Graphs](http://morrisjs.github.io/morris.js/bars.html) the various options are:
- hoverCallback: Reformat the whole 'hover' output
- labels: (already required) Labels for the y-axis keys

The best option might be to generically support all options. eg.
```js
// Default and custom options
var options = {
  element: elem,
  data: scope.areaData,
  xkey: scope.areaXkey,
  ykeys: scope.areaYkeys,
  labels: scope.areaLabels,
  lineColors: scope.lineColors || ['#0b62a4', '#7a92a3', '#4da74d', '#afd8f8', '#edc240', '#cb4b4b', '#9440ed']
};

// Apply known optons from morris.js doco
angular.forEach(['hoverCallback', 'units', 'postUnits', 'preUnits' /* etc. */], function(key) {
  if (scope.hasOwnProperty(key)) {
    options[key] = scope[key];
  }
});

// Apply any Angular specific sugar, like using filters for formatters
if (options.hasOwnProperty('xLabelFormat') && typeof options.xLabelFormat === 'string' && $injector.has(options.xLabelFormat + 'Filter')) {
  // If the formatter is a string, check for a matching filter
  var filter = $injector.get(options.xLabelFormat + 'Filter');
  options.xLabelFormat = function (input) {
    return filter.call(this, input);
  };
}

scope.areaInstance = new Morris.Area(options);
```

Thoughts?

**Comment by stewones** [comment]
good approach. i believe that's the way.

**Comment by rolaveric** [comment]
Cool.
One quick styling question then: Do you want to have a prefix for the attributes (eg. `area-hover-callback="" area-units=""`) or not?
Naming collisions are unlikely to be a problem since these are attributes on an element directive, but the existing attributes have all had prefixes.

**Comment by stewones** [comment]
Yes, you are right too.
But i think the prefixed style increases readability when used with html elements.

```html
<div
area-chart
area-data='[]'
area-xkey='y'
area-ykeys='["a", "b"]'
area-labels='["Serie A", "Serie B"]'
line-colors='["#31C0BE", "#c7254e"]'>
```
I believe the above code has a better visual look rather than below

```html
<div
area-chart
data='[]'
xkey='y'
ykeys='["a", "b"]'
labels='["Serie A", "Serie B"]'
line-colors='["#31C0BE", "#c7254e"]'>
```

but as in this case we have `line-colors` that not follows the prefixed style, (And i dont know why hu3hu3) what you decide, to me is fine.
