### ISSUE TITLE
Redraw donut chart after REST call

### ISSUE THREAD

**Issue by clabnet** [stewones/angular-morris-chart#36]
I have add your directive as is 

`  <div class="morris-chart" donut-chart donut-data="vm.donutData" donut-colors="['#23AE89','#2EC1CC','#FFB61C','#E94B3B']"></div>`

where my data are contained into vm.donutData.

I know the existence of the method "setData" into Morris chart, but I don't know how to pass the new .json at end of a call $http.

Any suggestion please ?

Thank's

**Comment by stewones** [comment]
hi @clabnet 

you dont have to use setData or instantiate Morris, the directive [does it internally](https://github.com/stewones/angular-morris-chart/blob/master/src/lib/directives/donutChart.directive.js#L59).

regardless of whether or not a REST call.

I'm closing because your problem has nothing to do with angular-morris

**Comment by stewones** [comment]
Hi @clabnet 

I have added this sample to docs. Maybe it can help you.

https://jsfiddle.net/stewones/xtuso6q8/

Feel free to open new issues.
